### ISSUE TITLE
Use appropriate Python version classifier in package

### ISSUE THREAD

**Issue by alex-dr** [smitchell556/pdb-attach#1]
https://pypi.org/classifiers/ lists available classifiers for setup.py

With no version classifier, it's easy to accidentally install this into a Python 2, or Python 3.4 environment, where it does not work.

Due to use of type hinting this package requires python 3.6 or greater, and that should be annotated.

**Comment by smitchell556** [comment]
Got it. I'll add those when I have a spare moment. As far as the type hints go, I'll probably move all type hints over to a stub file so as not to require a python version that supports them.

**Comment by smitchell556** [comment]
The Python version classifiers will be in the next release.
